apiVersion: v1
kind: ConfigMap
metadata:
  name: enduser-react
data:  
  REACT_APP_MSW_MOCK: {{ .Values.REACT_APP_MSW_MOCK }}
  NGINX_HOST: {{ .Values.NGINX_HOST }}
  REACT_APP_AUTH_BASE_URL: {{ .Values.REACT_APP_AUTH_BASE_URL }}
  REACT_APP_API_BASE_URL: {{ .Values.REACT_APP_API_BASE_URL }}
  REACT_APP_API_RESOURCES_URL: {{ .Values.REACT_APP_API_RESOURCES_URL }}
  REACT_APP_LOGO_URL: {{ .Values.REACT_APP_LOGO_URL }}
  REACT_APP_TITLE: {{ .Values.REACT_APP_TITLE }}
  REACT_APP_CLIENT_ICON_FOLDER: {{ .Values.REACT_APP_CLIENT_ICON_FOLDER }}
  REACT_APP_CLIENT_RGPD_REDIRECT: {{ .Values.REACT_APP_CLIENT_RGPD_REDIRECT }}
  REACT_APP_CLIENT_LOGO_REDIRECT_LINK: {{ .Values.REACT_APP_CLIENT_LOGO_REDIRECT_LINK | default "''" | quote }}
  ENVIRONMENT: {{ .Values.ENVIRONMENT }}
  REACT_APP_ANALYSIS_FEATURE_STATE: {{ .Values.REACT_APP_ANALYSIS_FEATURE_STATE }}
  REACT_APP_ADVICES_FEATURE_STATE: {{ .Values.REACT_APP_ADVICES_FEATURE_STATE }}
  REACT_APP_ADD_DELETE_HOUSING_FEATURE_STATE: {{ .Values.REACT_APP_ADD_DELETE_HOUSING_FEATURE_STATE }}
  REACT_APP_EQUIPMENTS_ACCOMODATION_FEATURE_STATE: {{ .Values.REACT_APP_EQUIPMENTS_ACCOMODATION_FEATURE_STATE }}
  REACT_APP_TEMP_PMAX_FEATURE_STATE: {{ .Values.REACT_APP_TEMP_PMAX_FEATURE_STATE }}
  REACT_APP_SGE_CONSENT_FEATURE_STATE: {{ .Values.REACT_APP_SGE_CONSENT_FEATURE_STATE }}
  REACT_APP_SGE_CONSENT_POPUP_MESSAGE: {{ .Values.REACT_APP_SGE_CONSENT_POPUP_MESSAGE }}
  REACT_APP_INSTALLATION_REQUESTS_FEATURE_STATE: {{ .Values.REACT_APP_INSTALLATION_REQUESTS_FEATURE_STATE }}
  REACT_APP_ENPHASE_CONSENT_FEATURE_STATE: {{ .Values.REACT_APP_ENPHASE_CONSENT_FEATURE_STATE }}
  REACT_APP_PRODUCTION_CHART_ERROR_STATE: {{ .Values.REACT_APP_PRODUCTION_CHART_ERROR_STATE }}
  REACT_APP_SOLAR_EQUIPMENTS_FEATURE_STATE: {{ .Values.REACT_APP_SOLAR_EQUIPMENTS_FEATURE_STATE }}
  REACT_APP_DELETE_ACCOUNT_FEATURE_STATE: {{ .Values.REACT_APP_DELETE_ACCOUNT_FEATURE_STATE }}
  REACT_APP_BASENAME_URL: {{ .Values.REACT_APP_BASENAME_URL }}
  REACT_APP_NOVU_BACKEND_URL: {{ .Values.REACT_APP_NOVU_BACKEND_URL }}
  REACT_APP_NOVU_SOCKET_URL: {{ .Values.REACT_APP_NOVU_SOCKET_URL }}
  REACT_APP_NOVU_APPLICATION_IDENTIFIER: {{ .Values.REACT_APP_NOVU_APPLICATION_IDENTIFIER }}  
  REACT_APP_FIREBASE_API_KEY: {{ .Values.REACT_APP_FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: {{ .Values.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_PROJECT_ID: {{ .Values.REACT_APP_FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_STORAGE_BUCKET: {{ .Values.REACT_APP_FIREBASE_STORAGE_BUCKET }}
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: {{ .Values.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
  REACT_APP_FIREBASE_APP_ID: {{ .Values.REACT_APP_FIREBASE_APP_ID }}
  REACT_APP_FIREBASE_VAPID_KEY: {{ .Values.REACT_APP_FIREBASE_VAPID_KEY }}
  REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.REACT_APP_GOOGLE_MAPS_API_KEY }} 
  REACT_APP_GENERAL_TERMS_OF_USE: {{ .Values.REACT_APP_GENERAL_TERMS_OF_USE }}
  REACT_APP_PRIVACY_POLICY: {{ .Values.REACT_APP_PRIVACY_POLICY }}
  REACT_APP_POPUP_AFTER_REGISTRATION: {{ .Values.REACT_APP_POPUP_AFTER_REGISTRATION | default "disabled" }}
  REACT_APP_ENERGY_PROVIDER_POPUP_LINK: {{ .Values.REACT_APP_ENERGY_PROVIDER_POPUP_LINK | default "''" }}
  REACT_APP_ENERGY_PROVIDER_REGISTER_MAPPING_KEYS: {{ .Values.REACT_APP_ENERGY_PROVIDER_REGISTER_MAPPING_KEYS | default "''" | quote }}
  REACT_APP_ENERGY_PROVIDER_NAME: {{ .Values.REACT_APP_ENERGY_PROVIDER_NAME | default "'notre fournisseur'" | quote }}
  REACT_APP_USER_REGISTRATION_FEATURE_STATE: {{ .Values.REACT_APP_USER_REGISTRATION_FEATURE_STATE }} 
  REACT_APP_USER_REGISTRATION_AUTO_VALIDATE: {{ .Values.REACT_APP_USER_REGISTRATION_AUTO_VALIDATE | default "false" | quote }} 
  REACT_APP_TECH_SUPPORT_ADDRESS: {{ .Values.REACT_APP_TECH_SUPPORT_ADDRESS }} 
  REACT_APP_GTM_ID: {{ .Values.REACT_APP_GTM_ID }}
  REACT_APP_PROFESSIONAL_REGISTER_FEATURE: {{.Values.REACT_APP_PROFESSIONAL_REGISTER_FEATURE | default "disabled" }}
  REACT_APP_ACTIVATE_CONTRACT_OTHER_PROVIDERS_AND_OFFERS: {{ .Values.REACT_APP_ACTIVATE_CONTRACT_OTHER_PROVIDERS_AND_OFFERS | default "enabled" }}
  REACT_APP_FAQ_REDIRECT_LINK: {{ .Values.REACT_APP_FAQ_REDIRECT_LINK }}