apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:  
  REACT_APP_MSW_MOCK: {{ .Values.configmap.REACT_APP_MSW_MOCK }}
  NGINX_HOST: {{ .Values.configmap.NGINX_HOST }}
  REACT_APP_AUTH_BASE_URL: {{ .Values.configmap.REACT_APP_AUTH_BASE_URL }}
  REACT_APP_API_BASE_URL: {{ .Values.configmap.REACT_APP_API_BASE_URL }}
  REACT_APP_API_RESOURCES_URL: {{ .Values.configmap.REACT_APP_API_RESOURCES_URL }}
  REACT_APP_LOGO_URL: {{ .Values.configmap.REACT_APP_LOGO_URL }}
  REACT_APP_TITLE: {{ .Values.configmap.REACT_APP_TITLE }}
  REACT_APP_CLIENT_ICON_FOLDER: {{ .Values.configmap.REACT_APP_CLIENT_ICON_FOLDER }}
  REACT_APP_CLIENT_RGPD_REDIRECT: {{ .Values.configmap.REACT_APP_CLIENT_RGPD_REDIRECT }}
  ENVIRONMENT: {{ .Values.configmap.ENVIRONMENT }}
  REACT_APP_ANALYSIS_FEATURE_STATE: {{ .Values.configmap.REACT_APP_ANALYSIS_FEATURE_STATE }}
  REACT_APP_ADVICES_FEATURE_STATE: {{ .Values.configmap.REACT_APP_ADVICES_FEATURE_STATE }}
  REACT_APP_ADD_DELETE_HOUSING_FEATURE_STATE: {{ .Values.configmap.REACT_APP_ADD_DELETE_HOUSING_FEATURE_STATE }}
  REACT_APP_EQUIPMENTS_ACCOMODATION_FEATURE_STATE: {{ .Values.configmap.REACT_APP_EQUIPMENTS_ACCOMODATION_FEATURE_STATE }}
  REACT_APP_TEMP_PMAX_FEATURE_STATE: {{ .Values.configmap.REACT_APP_TEMP_PMAX_FEATURE_STATE }}
  REACT_APP_SGE_CONSENT_FEATURE_STATE: {{ .Values.configmap.REACT_APP_SGE_CONSENT_FEATURE_STATE }}
  REACT_APP_INSTALLATION_REQUESTS_FEATURE_STATE: {{ .Values.configmap.REACT_APP_INSTALLATION_REQUESTS_FEATURE_STATE }}
  REACT_APP_ENPHASE_CONSENT_FEATURE_STATE: {{ .Values.configmap.REACT_APP_ENPHASE_CONSENT_FEATURE_STATE }}
  REACT_APP_PRODUCTION_CHART_ERROR_STATE: {{ .Values.configmap.REACT_APP_PRODUCTION_CHART_ERROR_STATE }}
  REACT_APP_SOLAR_EQUIPMENTS_FEATURE_STATE: {{ .Values.configmap.REACT_APP_SOLAR_EQUIPMENTS_FEATURE_STATE }}
  REACT_APP_DELETE_ACCOUNT_FEATURE_STATE: {{ .Values.configmap.REACT_APP_DELETE_ACCOUNT_FEATURE_STATE }}
  REACT_APP_BASENAME_URL: {{ .Values.configmap.REACT_APP_BASENAME_URL }}
  REACT_APP_NOVU_BACKEND_URL: {{ .Values.configmap.REACT_APP_NOVU_BACKEND_URL }}
  REACT_APP_NOVU_SOCKET_URL: {{ .Values.configmap.REACT_APP_NOVU_SOCKET_URL }}
  REACT_APP_NOVU_APPLICATION_IDENTIFIER: {{ .Values.configmap.REACT_APP_NOVU_APPLICATION_IDENTIFIER }}  
  REACT_APP_FIREBASE_API_KEY: {{ .Values.configmap.REACT_APP_FIREBASE_API_KEY }}
  REACT_APP_FIREBASE_AUTH_DOMAIN: {{ .Values.configmap.REACT_APP_FIREBASE_AUTH_DOMAIN }}
  REACT_APP_FIREBASE_PROJECT_ID: {{ .Values.configmap.REACT_APP_FIREBASE_PROJECT_ID }}
  REACT_APP_FIREBASE_STORAGE_BUCKET: {{ .Values.configmap.REACT_APP_FIREBASE_STORAGE_BUCKET }}
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: {{ .Values.configmap.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
  REACT_APP_FIREBASE_APP_ID: {{ .Values.configmap.REACT_APP_FIREBASE_APP_ID }}
  REACT_APP_FIREBASE_VAPID_KEY: {{ .Values.configmap.REACT_APP_FIREBASE_VAPID_KEY }}
  REACT_APP_GOOGLE_MAPS_API_KEY: {{ .Values.configmap.REACT_APP_GOOGLE_MAPS_API_KEY }} 

