apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "enduser-react.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "enduser-react.name" . }}
        helm.sh/chart: {{ include "enduser-react.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: {{ .Values.replicaCount | default 1 }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "enduser-react.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    template:
        metadata:
            annotations:
                # Forces a new pod rollout on each upgrade
                rollme: {{ randAlphaNum 5 | quote }}
            labels:
                app.kubernetes.io/name: {{ include "enduser-react.name" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            containers:
                - name: {{ include "enduser-react.name" . }}
                  image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
                  imagePullPolicy: {{ .Values.global.imagePullPolicy }}
                  ports:
                      - containerPort: 80
                  env:
{{- range $key, $value := .Values.env }}
                      - name: {{ $key }}
                        valueFrom:
                            configMapKeyRef:
                                name: {{ include "enduser-react.fullname" $ }}
                                key: {{ $key }}
{{- end }}
            imagePullSecrets:
                - name: dockersecret
