import { initializeApp } from 'firebase/app'
import { getMessaging, getToken } from 'firebase/messaging'

const firebaseConfig = {
    apiKey: 'AIzaSyClMER8hwr4e5l-br7DFKTGTZUnxwY42eg',
    authDomain: 'novu-push-notification.firebaseapp.com',
    projectId: 'novu-push-notification',
    storageBucket: 'novu-push-notification.appspot.com',
    messagingSenderId: '967242899838',
    appId: '1:967242899838:web:736824780e23ba1c17d32f',
}

// Initialize Firebase
const firebaseApp = initializeApp(firebaseConfig)
//Access Firebase cloud messaging
const messaging = getMessaging(firebaseApp)

/*
 */
/**
 * This function allows us to get your device token from Firebase, which is required for sending Push notifications to your device.
 *
 * @param onPermissionGranted Callback possibily send the token to backend, when token is generated by firebase.
 * @returns  Get Token From firebase.
 */
export const getTokenFromFirebase = (onPermissionGranted?: () => void) => {
    return getToken(messaging, {
        vapidKey: 'BJ2NTIROqDzc1nJzKAVJ-F9BABD-qlnjCp2bjHT5Bq2SzWJJkVH-5CCtsMHxnYGSiOGWoI6UUMOPx10HfdSuVCQ',
    }).then((currentToken) => {
        if (currentToken) {
            // SEND TO BACKEND.
            // console.log('current token for client: ', currentToken)
        }
        // else {
        // console.log('No registration token available. Request permission to generate one.')
        // }
    })
    // .catch((err) => {
    // console.error('An error occurred while retrieving token. ', err)
    // })
}
