#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#yarn run test -- --watchAll=false
#npx eslint . --fix --max-warnings=0
yarn pre-commit
npx tsc --skipLibCheck
yarn test --bail --watchAll=false --maxWorkers=2 --no-cache
