name: Continuous integration of enduser-react
# 
on:
    workflow_dispatch:
jobs:
  installdeps:
    name: Install deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          npm install -g yarn && yarn install && export NODE_OPTIONS="--max-old-space-size=8192
